### Введение в Numerical Python (NumPy)

### SciPy
**SciPy** (промовляється як “Сай Пай”) являє собою набір бібліотеки Python з відкритим вихідним кодом, що спеціалізується на наукових вичисленнях. Багато з цих бібліотек важливі і для аналізу даних. Разом вони складають набір інструментів для розрахунку та відображення даних.
Серед бібліотек, що знаходяться в групі SciPy, є деякі, які будуть обговорюватися на наступних заняттях::
 - NumPy
 - Matplotlib
 - Pandas



**NumPy: Коротка історія**<br>
На зорі мови Python розробникам стало потрібно проводити чисельні обчислення, особливо коли ця мова почала розглядатися науковим співтовариством. <br>
Першою спробою була Numeric, розроблена Джимом Гугуніним в 1995 році, за якою послідував альтернативний пакет під назвою Numarray. Обидва пакети були спеціалізованими для обчислення масивів, і кожен з них мав свої переваги залежно від того, в якому випадку вони були використані. Таким чином, їх застосовували по-різному, залежно від того, де вони виявилися більш ефективними. <br>Потім ця неоднозначність призвела до ідеї об’єднати два пакети, і тому Тревіс Оліфант почав розробляти бібліотеку NumPy. Перший випуск (v 1.0) відбувся у 2006 році.<br>
З цього моменту NumPy виявився бібліотекою розширень Python для наукових обчислень, і в даний час це найбільш широко використовуваний пакет для обчислення багатовимірних масивів та великих масивів. Крім того, пакет також постачається з низкою функцій, які дозволяють виконувати операції з масивами високоефективним способом та виконувати математичні розрахунки високого рівня. <br>
В даний час NumPy є відкритим кодом і ліцензується під BSD (Berkeley Software Distribution). Є багато авторів, які за їх підтримки розширили потенціал цієї бібліотеки.

**Ndarray: Ядро бібліотеки**<br>
NumPy є основною бібліотекою для наукових обчислень на Python. Він надає високопродуктивний багатовимірний об'єкт масиву та інструменти для роботи з цими масивами. Масив Numpy - це сітка значень, всі одного типу, що індексується набором цілих невід’ємних чисел. <br>

Базова бібліотека Python надавє списки Lists. List є еквівалентом масиву на Python, але його розмір може змінюватись і він може містити елементи різних типів.
<br>

Структури даних Numpy ефективніше працюють у наступних напрямках: <br>

  - Розмір - структури даних Numpy займають менше місця
  - Продуктивність - вони потребують швидкості і швидші за списки
  - Функціональність - SciPy та NumPy мають оптимізовані функції, такі як вбудовані операції лінійної алгебри.<br>

Вся бібліотека NumPy базується на одному основному об'єкті: **ndarray** (що означає N-мірний масив). Цей об’єкт є багатовимірним однорідним масивом із заздалегідь визначеною кількістю елементів: однорідним, оскільки практично всі елементи в ньому мають однаковий тип і однакового розміру. Насправді тип даних визначається іншим об’єктом NumPy, який називається **dtype** (тип даних); кожен ndarray пов'язаний лише з одним типом dtype. <br>
Кількість розмірів та елементів у масиві визначається його формою (**shape**), кортежем N-додатних цілих чисел, що визначає розмір кожного виміру. Розміри визначаються як осі, а кількість  (**axes**) - як ранг **rank**.
Більше того, ще однією особливістю масивів NumPy є те, що їх розмір є фіксованим, тобто, як тільки ви визначили їх розмір під час створення, він залишається незмінним. Ця поведінка відрізняється від списків Python, які можуть збільшуватися чи зменшуватися. <br>
Щоб визначити новий ndarray, найпростіший спосіб - скористатися функцією **array ()**, передавши список Python, що містить елементи, які повинні бути включені в нього як аргумент.
<br>
<br>

У цій лекції ми розглянемо кілька питань щодо основних маніпуляцій з масивами тут:<br>
- *Атрибути масивів*: Визначення розміру, форми, споживання пам'яті та типів масивів
- *Індексація масивів*: Отримання та встановлення значення окремих елементів масиву
- *Слайсинг масивів*: Отримання та встановлення менших підмасивів у межах більшого масиву
- *Зміна форми масивів*: Зміна форми даного масиву
- *Об'єднання та розбиття масивів*: Об'єднання декількох масивів в один та розбиття одного масиву на декілька

Спочатку давайте імпортуємо Numpy як np. Це дозволяє нам використовувати ярлик np для посилання на Numpy

In [1]:
import numpy as np


## Створення масивів

Створбємо список і перетворюємо його в масив numpy

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
print(x)

[1 2 3]


Або просто передаємо список безпосередньо

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Передаємо список списків, щоб створити багатовимірний масив.

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Ви можете легко перевірити, що новостворений об'єкт є ndarray, передаючи нову змінну функціїtype ().

In [5]:
type(a)

numpy.ndarray

Для того, щоб дізнатись асоційований dtype із щойно створеним ndarray, вам слід використовувати атрибут dtype.

In [6]:
a.dtype

dtype('int32')

На відміну від списків Python, NumPy обмежений масивами, які містять один тип. Якщо типи не збігаються, NumPy перетворить типи, якщо це можливо (тут цілі числа переміщуються до плаваючої крапки):

In [7]:
b = np.array([[1.,2.,3],[4,5,6]])
b.dtype

dtype('float64')

In [8]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
c=np.array(['a', 'b', 'c'] + [1, 2, 3])
c

array(['a', 'b', 'c', '1', '2', '3'], dtype='<U1')

Якщо ми хочемо явно встановити тип даних результуючого масиву, ми можемо використовувати ключове слово dtype:

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

## Стандартні типи даних NumPy

Масиви NumPy містять значення одного типу, тому важливо мати детальні знання про ці типи та їх обмеження.<br>
Оскільки NumPy побудований на C, типи будуть знайомі користувачам C, Fortran та інших суміжних мов.<br>

Стандартні типи даних NumPy перелічені в наступній таблиці.<br>

Зверніть увагу, що при побудові масиву їх можна вказати за допомогою рядка:<br>

```python
np.zeros(10, dtype='int16')
```

Або за допомогою асоційованого об’єкта NumPy:

```python
np.zeros(10, dtype=np.int16)
```

| Тип даних	    | Опис |
|---------------|-------------|
| ``bool_``     | Boolean (True або False), що зберігається як байт |
| ``int_``      | Цілочисельний тип за замовчуванням (такий же, як C``long``; як правило ``int64`` або ``int32``)| 
| ``intc``      | Ідентично C ``int`` (як правило ``int32`` або ``int64``)| 
| ``intp``      | Ціле число, що використовується для індексації (те саме, що C ``ssize_t``; як правило``int32`` або ``int64``)| 
| ``int8``      | Byte (від -128 до 127)| 
| ``int16``     | Ціле (від -32768 до 32767)|
| ``int32``     | Ціле (від -2147483648 доo 2147483647)|
| ``int64``     | Ціле (від -9223372036854775808 до 9223372036854775807)| 
| ``uint8``     | Ціле без знаку (від 0 до 255)| 
| ``uint16``    | Ціле без знаку (від 0 до 65535)| 
| ``uint32``    | Ціле без знаку (від 0 до 4294967295)| 
| ``uint64``    | Ціле без знаку (від 0 до 18446744073709551615)| 
| ``float_``    | Скорочення для ``float64``.| 
| ``float16``   | Число з рухомою комою половинної точності,знаковий біт, 5-бітна експонента, 10 біт мантиси| 
| ``float32``   | Число з рухомою комою одинарної точності,знаковий біт, 8-бітна експонента, 23 біти мантиси| 
| ``float64``   | Число з рухомою комою подвійної точності,знаковий біт, 11-бітна експонента, 52 біти мантиси| 
| ``complex_``  | Скорочення для ``complex128``.| 
| ``complex64`` | Комплексне число, представлене двома 32-бітними числами з рухомою комою| 
| ``complex128``| Комплексне число, представлене двома 64-бітними числами з рухомою комою| 

Можлива більш розширена специфікація типів, наприклад, вказівка порядку байтів в представленні числа; для отримання додаткової інформації зверніться [Документації NumPy](http://numpy.org/).


## Стврення масивів без використання списків

Особливо для більших масивів ефективніше створювати масиви без використання списків, використовуючи функції, вбудовані в NumPy. <br>Ось кілька прикладів::

In [11]:
# Створіть цілочисельний масив довжиною 10, заповнений нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Створіть масив із рухомою комою розміром 3x5, заповнений одиницями
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Створіть масив 3x5, заповнений 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# Створіть масив, заповнений лінійною послідовністю
# Починаючи з 0, закінчуючи 18, крокуючи по 2
# (це схоже на вбудовану функцію range ())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Створіть масив із п'яти значень, рівномірно розташованих між 0 і 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# Створіть масив 3x3 з рівномірно розподіленими
# випадковими значеннями від 0 до 1
np.random.random((3, 3))

array([[0.57868129, 0.2404469 , 0.89488461],
       [0.17999122, 0.23257899, 0.85906999],
       [0.33009134, 0.46817657, 0.75405002]])

In [17]:
# Створіть масив 3x3 із нормально розподіленими випадковими значеннями
# із середнім значенням 0 та стандартним відхиленням 1
np.random.normal(0, 1, (3, 3))

array([[ 0.22480946,  0.62703728,  3.11035012],
       [-1.39994939, -0.76840909,  0.82751229],
       [ 0.48504567, -0.17796868, -0.02164715]])

In [18]:
# Створіть 3x3 масив випадкових цілих чисел в інтервалі [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 3, 4],
       [3, 3, 0],
       [4, 5, 9]])

In [19]:
# Створіть одиничну матрицю 3х3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Створіть неініціалізований масив із трьох цілих чисел
# Значення будуть такими, які вже існують в області памяті
np.empty(3)

array([1., 1., 1.])

`diag` витягує діагональ або створює діагональний масив.

In [21]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [22]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [23]:
y = np.arange(9)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
y.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.diag(y.reshape(3,3))

array([0, 4, 8])

Створіть масив, використовуючи список, що повторюється

In [26]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Той самий результат дасть нам `np.tile`

In [27]:
np.tile([1,2,3],3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Повторіть елементи масиву, використовуючи `repeat`.

In [28]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Атрибути масиву
Спочатку обговоримо деякі корисні атрибути масиву. <br>
Ми почнемо з визначення трьох випадкових масивів, одновимірного, двовимірного та тривимірного масиву.<br> Ми будемо використовувати генератор випадкових чисел NumPy, який ми будемо створювати із заданим значенням, щоб переконатися, що генеруються однакові випадкові масиви кожного разу, коли запускається цей код:

In [29]:
np.random.seed(0)  # інструкція для відтворюваності

x1 = np.random.randint(10, size=6)  # Одновимірний масив
x2 = np.random.randint(10, size=(3, 4))  # Двовимірний масив
x3 = np.random.randint(10, size=(3, 4, 5))  # Тривимірний масив

Кожен масив має атрибути: <br>
- ndim (кількість осей),
- форма (розмір кожної осі),
- розмір (загальний розмір масиву):

In [30]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x1 ndim:  1
x1 shape: (6,)
x1 size:  6
x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Іншим корисним атрибутом є dtype, тип даних масиву (про який ми вже говорили раніше)

In [31]:
print("dtype:", x3.dtype)

dtype: int32


Інші атрибути включають `itemsize`, в якому перелічується розмір (у байтах) кожного елемента масиву, та `nbytes`, що містить загальний розмір (у байтах) масиву:

In [32]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


Загалом, ми очікуємо, що nbytes дорівнює величині розміру елементів помножене на розмір.

In [33]:
x3.nbytes == x3.itemsize * x3.size

True

### Індексація масиву: доступ до окремих елементів
Iндексація в NumPy не відрізняється від стандартною індексацією списків Python. В одновимірному масиві значення $i^{th}$ (відлік від нуля) можна отримати, вказавши бажаний індекс у квадратних дужках, як і у списках Python:


In [34]:
x1

array([5, 0, 3, 3, 7, 9])

In [35]:
x1[0]

5

In [36]:
x1[4]

7

In [37]:
x1[4]=-12
x1

array([  5,   0,   3,   3, -12,   9])

Для індексації з кінця масиву можна використовувати негативні індекси:

In [38]:
x1[-2]

-12

У багатовимірному масиві елементи можна отримати за допомогою набору індексів, розділених комами:

In [39]:
x2[2, -1]

7

Значення також можуть бути змінені за допомогою будь-якого із зазначених вище позначень індексу:

In [40]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Майте на увазі, що на відміну від списків Python **масиви NumPy мають фіксований тип**. Це означає, наприклад, що при спробі вставити значення з плаваючою комою в цілочисельний масив, значення буде мовчки скорочено!

In [41]:
x1[0] = 3.89  # це буде усічено!
x1

array([  3,   0,   3,   3, -12,   9])

При спробі призначення значення, тип якого не може бути перетвореним, буде помилка

In [42]:
x1[0] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

## Зрізи масиву: доступ до підмасивів

Подібно до того, як ми можемо використовувати квадратні дужки для доступу до окремих елементів масиву, ми також можемо використовувати їх для доступу до підмасивів із позначенням *зріз*, позначеним символом двокрапки (``:``).
Синтаксис слайсингу NumPy відповідає синтаксису стандартного списку Python; щоб отримати доступ до зрізу масиву `x`, використовуйте це:

``` python
x[start:stop:step]
```
Якщо будь-який із параметрів не вказано, значенням за замовчуванням є ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.<br>
Розглянемо доступ до підмасивів в одному вимірі та в декількох вимірах.


### Одновимірні підмасиви

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x[:5]  # перші п’ять елементів

array([0, 1, 2, 3, 4])

In [45]:
x[5:]  # елементи після індексу 5

array([5, 6, 7, 8, 9])

In [46]:
x[4:7]  # середній підмасив

array([4, 5, 6])

In [47]:
x[::2]  # кожен другий елемент

array([0, 2, 4, 6, 8])

In [48]:
x[1::2]  # кожен другий елемент, починаючи з індексу 1

array([1, 3, 5, 7, 9])

In [49]:
x[::-1]  # всі елементи в зворотному порядку

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
x[5::-2]  # елементи через один в зворотному порядку, починаючи з 5

array([5, 3, 1])

### Багатовимірні підмасиви

Багатовимірні підмасиви працюють таким же чином, при цьому кілька фрагментів розділяються комами.
Наприклад:

In [51]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [52]:
x2[:2, :3]  # два рядки, три стовпці

array([[12,  5,  2],
       [ 7,  6,  8]])

In [53]:
x2[:3, ::2]  # всі рядки, кожен другий стовпчик

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Нарешті, росташування елементів по осях підмасивів можна навіть змінити разом:

In [54]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Ще троху зрізів двовимірних масивів

In [55]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [56]:
r[3, 3:6]

array([21, 22, 23])

Тут ми вибираємо всі рядки до (і не враховуючи) рядка 2, і всі стовпці до (і не враховуючи) останнього стовпця.

In [57]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

Це зріз останнього рядка, і лише кожен другий елемент.

In [58]:
r[-1, ::2]

array([30, 32, 34])

Ми також можемо виконати умовне індексування. Тут ми вибираємо значення з масиву, які перевищують 30.

In [59]:
r[r > 30] 

array([31, 32, 33, 34, 35])

Використовуючи `np.where`, якщо значення масиву `r` менші за 10, то замінюємо їх на 0, в іншому випадку - залишаємо значення без змін

In [60]:
np.where(r<10,0,r)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Тут ми призначаємо всі значення в масиві, які перевищують 30, значенням 30.

In [61]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Підмасиви як подання без копіювання

Одне важливе і надзвичайно корисне знання про зрізи масиву - це те, що вони повертають *подання*, а не *копії* даних масиву.<br>
Це одна область, в якій зрізи масиву NumPy відрізняються від зрізів списків Python: у списках зрізи будуть копіями.<br>
Розглянемо наш двовимірний масив:


In [62]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Виріжемо з цього підмасив $ 2 \times 2 $:

In [63]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Тепер, якщо ми змінимо цей підмасив, то побачимо, що початковий масив змінено!

In [64]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [65]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Ця поведінка за замовчуванням насправді досить корисна: це означає, що коли ми працюємо з великими наборами даних, ми можемо отримувати доступ та обробляти фрагменти цих наборів даних без необхідності копіювати базовий буфер даних.

## Копіювання даних

Будьте обережні з копіюванням та зміною масивів у NumPy!


`r2` це зріз `r`

In [66]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [67]:
r is r2

False

Встановіть значення цього зрізу на нуль (`[:]` вибирає весь масив)

In [68]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` також було змінено!

In [69]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [70]:
id(r)

102014688

In [71]:
id(r2)

101867072

In [72]:
id(r) == id(r2)

False

In [73]:
r is r2

False

Щоб цього уникнути, використовуйте `r.copy`, щоб створити копію, яка не вплине на вихідний масив

In [74]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Тепер, коли r_copy змінено, r не буде змінено.

In [75]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Переформатування масивів

Ще одним корисним видом операції є переформатування масивів.<br>
Найбільш гнучкий спосіб зробити це за допомогою методу `reshape`.
Наприклад, якщо ви хочете помістити числа від 1 до 9 у сітку $ 3 \times 3 $, ви можете зробити наступне:


In [76]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Зверніть увагу, що для того, щоб це працювало, розмір початкового масиву повинен відповідати розміру переробленого масиву.<br>
Там, де це можливо, метод `reshape` використовуватиме подання початкового масиву без копіювання.<br>

Іншим поширеним шаблоном переформування є перетворення одновимірного масиву в двовимірну матрицю рядків або стовпців.
Це можна зробити за допомогою методу `reshape`, або легше зробити, використовуючи ключове слово `newaxis` в рамках операції зрізу:

In [77]:
x = np.array([1, 2, 3])

#  вектор-рядок за допомогою переформування
x.reshape((1, 3))

array([[1, 2, 3]])

In [78]:
# вектор-рядок за допомогою newaxis
y = x[np.newaxis, :]

In [79]:
# вектор-стовпчик, використовуючи reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [80]:
# вектор-стовпчик, використовуючи newaxis
y = x[:, np.newaxis]

In [81]:
y.shape

(3, 1)

`reshape` повертає масив з тими ж даними з новою фігурою.

In [82]:
n=np.arange(15)
nn = n.reshape(3, 5) # змінюємо форму масиву на 3x5
nn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Але форма мисиву залишається без змін

In [83]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

`resize` змінює форму та розмір масиву на місці


In [86]:
o=np.arange(10)

In [87]:
o.resize(3, 3)
o

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
o

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Різниця між `reshape` та `resize`: <br>
І `reshape`, і `resize` змінюють форму масиву numpy; різниця полягає в тому, що використання `resize` вплине на вихідний масив, тоді як за допомогою `reshape` створюється тільки нове змінене представлення масиву.

In [89]:
r = np.arange(16)
print('початковий r: \n',r)
print('\nreshaped масив: \n',r.reshape((4,4)))
print('\nмасив r після застосування reshape: \n',r)

початковий r: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped масив: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

масив r після застосування reshape: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [90]:
r = np.arange(16)
 
print('початковий r: \n',r)
print('\nresized масив: \n',r.resize((4,4)))
print('\nмасив r після застосування resize: \n',r)

початковий r: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

resized масив: 
 None

масив r після застосування resize: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Конкатенація та розділення масивів

Усі попередні процедури працювали над одиничними масивами. Також можна об'єднати декілька масивів в один і навпаки розділити один масив на кілька масивів. Ми поглянемо на ці операції тут.

### Об’єднання масивів

Конкатенація або об'єднання двох масивів у NumPy в основному здійснюється за допомогою підпрограм ` np.concatenate`, ` np.vstack` і ` np.hstack`.<br>
`np.concatenate` бере кортеж або список масивів як перший аргумент, як ми можемо бачити тут:

In [91]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate((x, y)))
print(np.concatenate([x, y]))

[1 2 3 3 2 1]
[1 2 3 3 2 1]


Ви також можете об'єднати більше двох масивів одночасно:

In [92]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


Він також може бути використаний для двовимірних масивів:

In [93]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [94]:
# об'єднати уздовж першої осі
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [95]:
# об'єднати уздовж другої осі
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Для роботи з масивами змішаних розмірів може бути зрозуміліше використовувати функції `np.vstack` (вертикальний стек) і `np.hstack` (горизонтальний стек):

In [96]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [97]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Подібно, ` np.dstack` буде додавати масиви уздовж третьої осі.

### Розбиття масивів

Протилежністю конкатенації є розділення, яке реалізується функціями `np.split`, `np.hsplit` і `np.vsplit`. Для кожної з них ми можемо передати список індексів, що дають точки поділу:

In [98]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Зверніть увагу, що *N* точки поділу ведуть до *N + 1* підмасивів.
Пов'язані функції `np.hsplit` та  `np.vsplit` подібні:

In [99]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [100]:
upper, middle, lower = np.vsplit(grid, [1,3])
print(upper)
print(middle)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [101]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]



## Операції

Використовуйте `+`, `-`,` * `,` / `та` ** `, щоб виконати поелементне додавання, віднімання, множення, ділення та піднесення у степінь.

In [102]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [103]:
print(x + y) # поелементне додавання     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # поелементне віднімання  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [104]:
print(x * y) # поелементне множення  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # поелементне ділення         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [105]:
print(x**2) # поелементне піднесення у степінь  [1 2 3] ^2 =  [1 4 9]

[1 4 9]



**Матричне множення:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [106]:
x.dot(y) # Матричне множення  1*4 + 2*5 + 3*6

32

In [107]:
x @ y

32

In [108]:
a = np.arange(0,6).reshape(2,3)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)


[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [109]:
a @ b

array([[ 28,  31],
       [100, 112]])

Давайте розглянемо транспонування масивів. Транспонування переставляє розміри масиву.

In [110]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

Розміри матриці `z` це `(2,3)` перед транспонуванням.

In [111]:
z.shape

(2, 3)

Використовуйте `.T`, щоб отримати транспонування.

In [112]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [113]:
z.T.shape

(3, 2)

Використовуйте `.dtype`, щоб побачити тип даних елементів у масиві.

In [114]:
z.dtype

dtype('int32')

Використовуйте ".astype", щоб передати певний тип.

In [115]:
z = z.astype('f')
z.dtype

dtype('float32')

Щоб отримати довідку, введіть `np.info (деяка_функція)`

In [116]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,